# Generated by Django 5.0.1 on 2024-01-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstockaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realcashtransfer',
            options={'verbose_name': 'Giao dịch tiền thật', 'verbose_name_plural': 'Giao dịch tiền thật'},
        ),
    ]
