# Generated by Django 5.0.1 on 2024-01-13 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstockaccount', '0003_realtradingpower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealCashTransfer',
            new_name='RealStockAccountCashTransfer',
        ),
        migrations.AlterModelOptions(
            name='realstockaccountcashtransfer',
            options={'verbose_name': 'Sao kê tiền TKCK thật', 'verbose_name_plural': 'Sao kê tiền TKCK thật'},
        ),
        migrations.CreateModel(
            name='RealBankCashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='TCB', max_length=20, verbose_name='Tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nộp tiền')),
                ('amount', models.FloatField(verbose_name='Số tiền')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('user_modified', models.CharField(blank=True, max_length=150, null=True, verbose_name='Người chỉnh sửa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sao kê tiền TKNH thật',
                'verbose_name_plural': 'Sao kê tiền TKNH thật',
            },
        ),
    ]
