# Generated by Django 5.0.1 on 2024-01-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationregulations',
            options={'verbose_name': 'Quy định hoạt động', 'verbose_name_plural': 'Quy định hoạt động'},
        ),
    ]
