# Generated by Django 5.0.1 on 2024-01-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotrading', '0002_dividendmanage_delete_stockprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datenottrading',
            options={'verbose_name': 'Ngày lễ không giao dịch', 'verbose_name_plural': 'Ngày lễ không giao dịch'},
        ),
        migrations.AlterModelOptions(
            name='dividendmanage',
            options={'verbose_name': 'Quản lí cổ tức', 'verbose_name_plural': 'Quản lí cổ tức'},
        ),
        migrations.AlterModelOptions(
            name='stockpricefilter',
            options={'verbose_name': 'Giá thị trường', 'verbose_name_plural': 'Giá thị trường'},
        ),
    ]
