# Generated by Django 5.0.1 on 2024-01-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpd', '0002_alter_clientpartnerinfo_commission_and_more'),
        ('operation', '0002_portfolio_market_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referrer',
        ),
        migrations.AddField(
            model_name='account',
            name='cpd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpd.clientpartnerinfo', verbose_name='Người giới thiệu'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_pl',
            field=models.FloatField(default=0, verbose_name='Tổng lời lỗ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_fee',
            field=models.FloatField(default=0.16, verbose_name='Lãi suất'),
        ),
    ]
