# Generated by Django 5.0.1 on 2024-01-12 10:07

import operation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_account_referrer_account_cpd_account_total_pl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxTradingPowerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lí sức mua',
                'verbose_name_plural': 'Quản lí sức mua',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operation.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.FloatField(default=operation.models.get_credit_limit_default, verbose_name='Hạn mức mua'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_closed_pl',
            field=models.FloatField(default=0, verbose_name='Tổng lời lỗ đã chốt'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_interest_paid',
            field=models.FloatField(default=0, verbose_name='Tổng lãi vay đã trả'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_temporarily_interest',
            field=models.FloatField(default=0, verbose_name='Tổng lãi vay tạm tính'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_temporarily_pl',
            field=models.FloatField(default=0, verbose_name='Tổng lời lỗ tạm tính'),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_fee',
            field=models.FloatField(default=operation.models.get_interest_fee_default, verbose_name='Lãi suất'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax',
            field=models.FloatField(default=operation.models.get_tax_fee_default, verbose_name='Thuế'),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_loan_interest',
            field=models.FloatField(default=0, verbose_name='Tổng lãi vay'),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_fee',
            field=models.FloatField(default=operation.models.get_transaction_fee_default, verbose_name='Phí giao dịch'),
        ),
    ]
