# Generated by Django 5.0.1 on 2024-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_maxtradingpoweraccount_account_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_t0',
            field=models.FloatField(default=0, verbose_name='Số dư tiền bán đã về'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_buy_trading_value',
            field=models.FloatField(default=0, verbose_name='Tổng giá trị mua'),
        ),
    ]
