# Generated by Django 5.0.1 on 2024-01-18 20:20

import django.db.models.deletion
import operation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_account_cash_t0_account_total_buy_trading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestatement',
            name='type',
            field=models.CharField(choices=[('interest', 'Lãi vay'), ('transaction_fee', 'Phí giao dịch'), ('tax', 'Thuế bán')], max_length=50, verbose_name='Loại phí'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='position',
            field=models.CharField(choices=[('buy', 'Mua'), ('sell', 'Bán')], max_length=4, verbose_name='Mua/Bán'),
        ),
        migrations.CreateModel(
            name='AccountMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.IntegerField(verbose_name='Giai đoạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('interest_fee', models.FloatField(default=operation.models.get_interest_fee_default, verbose_name='Lãi suất')),
                ('transaction_fee', models.FloatField(default=operation.models.get_transaction_fee_default, verbose_name='Phí giao dịch')),
                ('tax', models.FloatField(default=operation.models.get_tax_fee_default, verbose_name='Thuế')),
                ('net_cash_flow', models.FloatField(default=0, verbose_name='Nạp rút tiền ròng')),
                ('cash_balance', models.FloatField(default=0, verbose_name='Số dư tiền')),
                ('nav', models.FloatField(default=0, verbose_name='Tài sản ròng')),
                ('margin_ratio', models.FloatField(default=0, verbose_name='Tỷ lệ margin')),
                ('excess_equity', models.FloatField(default=0, verbose_name='Dư kí quỹ')),
                ('pre_interest_cash_balance', models.FloatField(default=0, verbose_name='Số dư tiền tính lãi')),
                ('interest_paid', models.FloatField(default=0, verbose_name='Tổng lãi vay đã trả')),
                ('closed_pl', models.FloatField(default=0, verbose_name='Tổng lời lỗ đã chốt')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Mốc Tài khoản',
                'verbose_name_plural': 'Mốc Tài khoản',
            },
        ),
    ]
