# Generated by Django 5.0.1 on 2024-01-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_expensestatement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmilestone',
            name='margin_ratio',
        ),
    ]
