# Generated by Django 5.0.1 on 2024-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_remove_accountmilestone_margin_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='milestone_date_lated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày tất toán gần nhất'),
        ),
    ]
