# Generated by Django 5.0.1 on 2024-01-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_account_milestone_date_lated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmilestone',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='accountmilestone',
            name='excess_equity',
        ),
        migrations.RemoveField(
            model_name='accountmilestone',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='accountmilestone',
            name='pre_interest_cash_balance',
        ),
        migrations.AddField(
            model_name='accountmilestone',
            name='net_trading_value',
            field=models.FloatField(default=0, verbose_name='Giao dịch ròng'),
        ),
        migrations.AddField(
            model_name='accountmilestone',
            name='total_buy_trading_value',
            field=models.FloatField(default=0, verbose_name='Tổng giá trị mua'),
        ),
    ]
